# Generated by Django 4.2.2 on 2023-06-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicfile',
            old_name='owner',
            new_name='uploader',
        ),
        migrations.AlterField(
            model_name='musicfile',
            name='allowed_emails',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.user')),
            ],
        ),
    ]
